name: gazelle_hosting_plugin
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  gazelle_core: ^0.4.0
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_static: ^1.1.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
