name: gazelle_hosting_plugin
version: 1.0.1
description: A simple plugin for hosting static files with the Gazelle framework.
homepage: https://github.com/GregoryPardini/gazelle_hosting_plugin
repository: https://github.com/GregoryPardini/gazelle_hosting_plugin
issue_tracker: https://github.com/GregoryPardini/gazelle_hosting_plugin/issues


environment:
  sdk: '>=3.3.2 <4.0.0'

# Add regular dependencies here.
dependencies:
  gazelle_core: ^0.6.0
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_static: ^1.1.2

  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  mockito: ^5.0.0
  build_runner: ^2.0.0

